# Generated by Django 4.1.4 on 2022-12-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
